### ISSUE TITLE
[BUG]: PORTS removed after refreshing ROMs

### ISSUE THREAD

**Issue by South204** [rkr87/aroma#128]
After initial ROM Refresh, the PORTS icon has been removed from the Games section of Crossmix.

Crossmix 1.2.1

Reproduce :
Load any games into PORTS (from Portmaster)
Run ROM refresh in Aroma

**Comment by rkr87** [comment]
Thanks for raising.

Could you attach a copy of the romdb.json and log.txt files in your aroma app folder, please?

**Comment by rkr87** [comment]
Problem identified:
https://github.com/rkr87/aroma/blob/master/src/aroma/aroma/manager/emu_manager.py#L68

Resolution:
Move this check from is_valid_system to is_configurable_system.

I'll apply a fix next time I'm at my PC.

**Comment by rkr87** [comment]
I've applied a fix for this issue, you may need to delete your romdb.json before refreshing with the new version.

For my own reference, this relates to wider issues captured in #125.
