### ISSUE TITLE
[BUG]: Refreshing ROMs with aROMa messes up their names

### ISSUE THREAD

**Issue by firinael** [rkr87/aroma#238]
I've specifically set my ROMs' names to be just the title of the game, by changing both the file name and using Skraper to set all the titles in the metadata as such. However, refreshing ROMs using aROMa for some reason adds back the filler like the region and such, despite me not choosing to display these.

**Comment by rkr87** [comment]
aROMa uses its own metadata to display names in the OS by default and completely ignores your file names unless told to use those instead.

The "title" format code is the full title of the file (IE includes region etc), if you just want the name of the game, use the "name" format code ($n).

If you prefer, you can disable aROMa using it's own metadata and instead generate display names using the file names by setting "console ROM naming" to stock.

You probably just need to set the format codes appropriately, though.

**Comment by firinael** [comment]
Oh I'm just dumb then, my apologies. Thank you!
